title: "Fathinah Asma Izzati"
email: fathinah.asma@ui.ac.id
description: >- # this means to ignore newlines until "baseurl:"
  I (20) am a computer science junior at one of the top universities in Indonesia with 2+ years of programming experience in Python and Java. From prior 
  internships, numerous projects, and school courses, I have gained a solid fundamental of big data analytics and architecture, image processing, and
  machine learning. I am also well-adapt with the math concept and application of ML supervised, unsupervised, and deep learning models on a large
  dataset in Python. I am an adaptable, proactive problem solver, aspiring data enthusiast with a strong analytical, verbal, and written skill, and a sense of
  humor, who value collaboration to create meaningful impacts.
# Root directory for your portfolio. On GitHub Pages, this is the name of your repository.
baseurl: "/portfolio"
# Protocol + hostname for your portfolio. On GitHub Pages, this is https://yourusername.github.io
url: "https://fathinah.github.io" 
github_username: fathinah
form_url: "https://formspree.io/f/xrgodpqo"
social_image: "./assets/img/social-link.jpg"
social_image_alt: # Alt text for the link preview image
google_analytics_measurement_id: # G-XXXXXXXXXX

sass:
  sass_dir: _sass

icon: ./assets/img/profile.jpeg
